//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildDispalySchoolEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Children = new HashSet<Child>();
            this.Children1 = new HashSet<Child>();
            this.Children2 = new HashSet<Child>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] SignatureImage { get; set; }
        public string LandlineFixed { get; set; }
        public string OfficeFixed { get; set; }
        public string OfficeExtension { get; set; }
        public string FaxFixed { get; set; }
        public string MobileFixed { get; set; }
        public string Email { get; set; }
        public string StreetNum { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string BillingStreetNum { get; set; }
        public string BillingAddress { get; set; }
        public string BillingSuburb { get; set; }
        public string BillingCity { get; set; }
        public string BillingPostcode { get; set; }
        public string BillingCountry { get; set; }
        public string OscarNum { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Relation { get; set; }
        public string HowHear { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
        public bool FirstAidCheck { get; set; }
        public Nullable<System.DateTime> FirstAidExpireyDate { get; set; }
        public bool PoliceCheck { get; set; }
        public Nullable<System.DateTime> PoliceCheckExprieyDate { get; set; }
        public Nullable<bool> ChildcareCertificate { get; set; }
        public Nullable<System.DateTime> ChildcareCertiIssueDate { get; set; }
        public string ChildCareCertiNum { get; set; }
        public string Notes { get; set; }
        public string DriverLicence { get; set; }
        public string Landline { get; set; }
        public string Office { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string SocialWorkerId { get; set; }
        public string OtherRelation { get; set; }
        public string IDNumber { get; set; }
        public string InsurancePlanOption { get; set; }
        public string MedicalAidProvider { get; set; }
        public string MedicalNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children2 { get; set; }
    }
}
