//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildDispalySchoolEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.Children = new HashSet<Child>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SchoolNumber { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Principal { get; set; }
        public string Website { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalAddress3 { get; set; }
        public string PostalCode { get; set; }
        public string UrbanArea { get; set; }
        public string SchoolType { get; set; }
        public string Definition { get; set; }
        public string Authority { get; set; }
        public string GenderOfStudents { get; set; }
        public string TerritorialAuthority { get; set; }
        public string RegionalCouncil { get; set; }
        public string MinistryOfEducationLocalOffice { get; set; }
        public string EducationRegion { get; set; }
        public string Ward { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> Decile { get; set; }
        public Nullable<int> TotalRoll { get; set; }
        public Nullable<int> EuropeanPakeha { get; set; }
        public Nullable<int> Maori { get; set; }
        public Nullable<int> Pasifika { get; set; }
        public Nullable<int> Asian { get; set; }
        public Nullable<int> MELAA { get; set; }
        public Nullable<int> OtherEthnicity { get; set; }
        public Nullable<int> InternationalStudents { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string DefaultTimeZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
        public virtual School School1 { get; set; }
        public virtual School School2 { get; set; }
    }
}
